#!/usr/bin/env python

# pip install anthropic

from common import *
import anthropic
from llm_actor.anthropic import Conversation

# model = "claude-3-haiku-20240307" # doesn't know Jennifer Bolt
model = "claude-3-5-haiku-20241022"
# model = "claude-3-7-sonnet-20250219"

api_key = os.getenv("ANTHROPIC_API_KEY")
ai = anthropic.Anthropic(api_key=api_key)
conv = Conversation(ai, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
