#!/usr/bin/env python

# pip install google-genai

from common import *
from google import genai
from llm_actor.gemini import Conversation

model = "gemini-2.0-flash-lite-preview-02-05"
# model = "gemini-2.0-flash"
# model = "gemini-2.0-pro-exp-02-05"
# model = "gemini-2.0-flash-thinking-exp-01-21"
# model = "gemini-1.5-flash-8b"

api_key = os.getenv("GOOGLE_API_KEY")
ai = genai.Client(api_key=api_key)
conv = Conversation(ai, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
