#!/usr/bin/env python

# pip install openai

from common import *
from openai import OpenAI
from llm_actor.openai.responses import Conversation

model = "gpt-4o-mini"
# model = "o3-mini"
# model = "gpt-4o"
# model = "o1"

ai = OpenAI()
conv = Conversation(ai, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
