#!/usr/bin/env python

# pip install openai

from common import *
import openai
from llm_actor.deepseek import Conversation

model = "deepseek-chat" # DeepSeek-V3
# model = "deepseek-reasoner" # DeepSeek-R1

api_key = os.getenv("DEEPSEEK_API_KEY")
ai = openai.OpenAI(api_key=api_key, base_url="https://api.deepseek.com/v1")
conv = Conversation(ai, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
