#!/usr/bin/env python

from common import *
import openai
from llm_actor.deepseek import Conversation

api_key = os.getenv("DEEPSEEK_API_KEY")
ai = openai.OpenAI(api_key=api_key, base_url="https://api.deepseek.com/v1")

model = "deepseek-chat" # DeepSeek-V3
# model = "deepseek-reasoner" # DeepSeek-R1

system_message="""
You are a knowledgeable and articulate AI assistant.
Keep your answer very consice. Do not provide extra information unless asked.
"""

conv = Conversation(ai, model=model, prolog=system_message)
try:
	print(conv.ask("which runner holds the world record in 100m race?"))
	print(conv.ask("what is his mother's name?"))
except Exception as x:
    sys.excepthook(type(x), x, x.__traceback__)
    exit(1)

print('---')
print(conv.messages)
print('---')
print_json(data=conv.conversation())
