#!/usr/bin/env python

# pip install langchain-community langchain-openai
# https://python.langchain.com/docs/integrations/chat/openai

import os
from langchain_openai import ChatOpenAI
from llm_actor.langchain import Conversation

model = "gpt-4o-mini"

chat = ChatOpenAI(model=model, temperature=0)
conv = Conversation(chat)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
