#!/usr/bin/env python

# pip install langchain-community langchain-deepseek
# https://python.langchain.com/docs/integrations/chat/deepseek/

import os
from langchain_deepseek import ChatDeepSeek
from llm_actor.langchain import Conversation

model = "deepseek-chat" # DeepSeek-V3

chat = ChatDeepSeek(model_name=model, temperature=0)
conv = Conversation(chat)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
