#!/usr/bin/env python

# pip install langchain-community langchain-ollama

from common import *
from langchain_ollama import ChatOllama
from llm_actor.langchain import Conversation

# model = "mistral:7b"
# model = "gemma3:4b"
# model = "llama3.1:8b"
# model = "deepseek-r1:8b"
model = "qwq:32b"

chat = ChatOllama(model=model, temperature=0, n_gpu_layers=-1)
conv = Conversation(chat, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
