#!/usr/bin/env python

# pip install langchain-community langchain-google-genai

import os
from langchain_google_genai import GoogleGenerativeAI
from llm_actor.langchain import Conversation

model = "gemini-2.0-flash-lite-preview-02-05"
# model = "gemini-2.0-flash-lite"
# model = "gemini-2.0-flash"
# model = "gemini-1.5-flash-8b"

chat = GoogleGenerativeAI(model=model, temperature=0)
conv = Conversation(chat, model=model)

def ask(q):
    print(q)
    print(conv.ask(q))

ask("which runner holds the world record in 100m race?")
ask("what is his mother's name?")
conv.print_summary()
