#!/usr/bin/env python

import os
import sys
from llm_actor import Prolog
import tiktoken

if len(sys.argv) > 1:
    fname = sys.argv[1]
else:
    fname = "prologs/apprentice-system.1"
prolog = str(Prolog(fname))
print("\n" + prolog)

model = os.getenv("MODEL", "gpt-4o-mini")
try:
    enc = tiktoken.encoding_for_model(model)
except:
    enc = tiktoken.get_encoding(model)

ntok = len(enc.encode(prolog))
print(f"={len(prolog)} [{ntok}]")
