#!/usr/bin/env python

# pip install anthropic

import os
import traceback
import anthropic
from llm_actor.anthropic import Conversation
from llm_actor import Actor, Prolog

api_key = os.getenv("ANTHROPIC_API_KEY")
ai = anthropic.Anthropic(api_key=api_key)

# model = "claude-3-haiku-20240307" # does not get the apprentice instructions right
model = "claude-3-5-haiku-20241022"
# model = "claude-3-7-sonnet-20250219"

space = "spaces/001"

prolog = Prolog("prologs/apprentice-system.1")
conv = Conversation(ai, model=model, prolog=str(prolog))
act = Actor(conv, space=space)
try:
    print(act.ask("How long (in lines) is the program in x1.c?"))
    print(act.ask("will the code compile?"))
except Exception as x:
    print(x)
    traceback.print_exc()
    exit(1)
    

print('---')
print(conv.messages)
