#!/usr/bin/env python

# pip install google-genai

import os
from google import genai
from gemini import Conversation
from actor import Actor

api_key = os.getenv("GOOGLE_API_KEY")
ai = genai.Client(api_key=api_key)

# model = "gemini-2.0-flash-lite-preview-02-05" # fails to detect C error
# model = "gemini-2.0-flash" # fails to understand instuctions
model = "gemini-2.0-flash-thinking-exp-01-21" # very good. only explains when asked.
# model = "gemini-2.0-pro-exp-02-05"
# model = "gemini-1.5-flash-8b" # fails to understand instructions
# model = "gemma-3-27b-it" # no instructions yet

system_message_file = "apprentice-system.1"
with open(system_message_file, "r") as file:
    system_message = file.read()
conv = Conversation(ai, model=model, prolog=system_message)
act = Actor(conv)
try:
    print(act.ask("How long (in lines) is the program in x1.c?"))
    print(act.ask("will the code compile?"))
except Exception as x:
    print(x)

print('---')
print(conv.messages)
