#!/usr/bin/env python

from openai import OpenAI
from openai_responses import Conversation
from actor import Actor

model = "gpt-4o"
# model = "gpt-4o-mini"  # has comprehention problems
# model = "o3-mini" # has comprehention problems
# model = "o1"

system_message_file = "apprentice-system.1"
with open(system_message_file, "r") as file:
    system_message = file.read()

ai = OpenAI()
conv = Conversation(ai, model, system_message)
act = Actor(conv)
try:
    print(act.ask("How long (in lines) is the program in x1.c?"))
except Exception as x:
    print(x)
print('---')
print(conv.messages)
