#!/usr/bin/env python

# pip install anthropic

from common import *
import anthropic
from llm_actor.anthropic import Conversation
from llm_actor import Actor, Prolog

# model = "claude-3-haiku-20240307" # does not get the apprentice instructions right
model = "claude-3-5-haiku-20241022"
# model = "claude-3-7-sonnet-20250219"

space = "../llm-actor-spaces/spaces/001"

api_key = os.getenv("ANTHROPIC_API_KEY")
ai = anthropic.Anthropic(api_key=api_key)
prolog = Prolog("prologs/apprentice-system.1")
conv = Conversation(ai, model=model, prolog=prolog)
act = Actor(conv, space=space)

def ask(q):
    print(q)
    print(act.ask(q))

ask("How long (in lines) is the program in x1.c?")
ask("will the code compile? explain!")
act.print_summary()
