#!/usr/bin/env python

# pip install openai

from common import *
import openai
from llm_actor.deepseek import Conversation
from llm_actor import Actor, Prolog


model = "deepseek-chat" # DeepSeek-V3
# model = "deepseek-reasoner" # DeepSeek-R1

space = "../llm-actor-spaces/spaces/001"

api_key = os.getenv("DEEPSEEK_API_KEY")
ai = openai.OpenAI(api_key=api_key, base_url="https://api.deepseek.com/v1")
prolog = Prolog("prologs/apprentice-system.1")
conv = Conversation(ai, model=model, prolog=prolog)
act = Actor(conv, space=space)

def ask(q):
    print(q)
    print(act.ask(q))

ask("How long (in lines) is the program in x1.c?")
ask("will the code compile? explain!")
act.print_summary()
