#!/usr/bin/env python

# pip install google-genai

from common import *
from google import genai
from llm_actor.gemini import Conversation
from llm_actor import Actor, Prolog

# model = "gemini-2.5-pro-exp-03-25"
# model = "gemini-2.0-flash-lite-preview-02-05" # fails to detect C error
# model = "gemini-2.0-flash" # fails to understand instuctions
model = "gemini-2.0-flash-thinking-exp-01-21" # very good. only explains when asked.
# model = "gemini-2.0-pro-exp-02-05"
# model = "gemini-1.5-flash-8b" # fails to understand instructions
# model = "gemma-3-27b-it" # no instructions yet

space = "../llm-actor-spaces/spaces/001"

api_key = os.getenv("GOOGLE_API_KEY")
ai = genai.Client(api_key=api_key)
prolog = Prolog("prologs/apprentice-system.1")
conv = Conversation(ai, model=model, prolog=prolog)
act = Actor(conv, space=space)

def ask(q):
    print(q)
    print(act.ask(q))

ask("How long (in lines) is the program in x1.c?")
ask("will the code compile? explain!")
act.print_summary()
