#!/usr/bin/env python

# pip install openai

from common import *
from openai import OpenAI
from llm_actor.openai.responses import Conversation
from llm_actor import Actor, Prolog

model = "gpt-4o"
# model = "gpt-4o-mini"  # has comprehention problems
# model = "o3-mini" # has comprehention problems
# model = "o1"

space = "../llm-actor-spaces/spaces/001"

ai = OpenAI()
prolog = Prolog("prologs/apprentice-system.1")
conv = Conversation(ai, model=model, prolog=prolog)
act = Actor(conv, space=space)

def ask(q):
    print(q)
    print(act.ask(q))

ask("How long (in lines) is the program in x1.c?")
ask("will the code compile? explain!")
act.print_summary()
